name: Docker CI

on:
  push:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t miapp ./challenge11
    - name: Run container
      run: docker run --rm miapp
